apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mood-portal
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: mood-portal
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-portal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-portal
        apps.tanzu.vmware.com/workload-type: dekt-url
        carto.run/workload-name: mood-portal
    spec:
      containers:
      - env:
        - name: SENSORS_ACTIVATE_API
          value: http://mood-sensors.dev.openso.online/activate
        - name: SENSORS_MEASURE_API
          value: http://mood-sensors.dev.openso.online/measure
        image: harbor.tanzuworld.com/tap-dev/mood-portal-myteam@sha256:8e5e3b8f36918d553e1ba438de399f3aaf158b902eeeda3a21f0fec336039ba0
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

